name: CI Test Workflow

on:
  workflow_dispatch:   # ← 手動実行を許可
  workflow_run:        # ← workflow_jobの前提（別Workflowに依存する場合）

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions"
