name: Dynamic EC2 Runner Workflow

on: workflow_dispatch

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    outputs:
      runner_name: ${{ steps.invoke-lambda.outputs.runner_name }}
    steps:
      - name: Invoke Lambda to start EC2 runner
        id: invoke-lambda
        run: |
          response=$(curl -s -X POST https://mjpltpz29l.execute-api.ap-northeast-1.amazonaws.com/runner/start)
          echo "$response"
          echo "runner_name=$(echo $response | jq -r .runnerName)" >> $GITHUB_OUTPUT

  main-job:
    needs: setup-runner
    runs-on: [self-hosted, "${{ needs.setup-runner.outputs.runner_name }}"]
    steps:
      - name: Main task
        run: echo "Running on ${{ runner.name }}"

  cleanup:
    if: always()
    needs: [setup-runner, main-job]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Lambda to stop EC2 runner
        run: |
          curl -X POST https://mjpltpz29l.execute-api.ap-northeast-1.amazonaws.com/runner/stop \
            -H "Content-Type: application/json" \
            -d '{"workflow_job": { "runner_name": "${{ needs.setup-runner.outputs.runner_name }}" }}'
